apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: quotebook-letsencrypt-staging
spec:
  secretName: quotebook-letsencrypt-staging-tls
  issuerRef:
    name: letsencrypt-staging
  commonName: quotebook.xyz
  acme:
    config:
    - http01:
        ingress: quotebook-ingress
      domains:
      - quotebook.xyz
